# Loads default set of integrations. Do not remove.
default_config:

# Loads default cloud integration
cloud:

bluetooth:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/button-text-card/button-text-card.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# For ios specific advanced notifications
ios:
